### PR TITLE
Ready for Review

### PR DESCRIPTION
**Pull request by Morrism1**
## Responsive#2 Newsweek Clone
- Added a header and navbar using bootstrap
- Added different news sections also using bootstrap where I can
- Added footer elements 
- Positioned elements with grid and flexbox

[Live Version](https://morrism1.github.io/Responsive-Newsweek/)

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @Morrism1, congratulations on your first attempt 👍 The project looks great 👌 However, we can improve the project and make it, even more, better by working on the comments below: 
* ```In small screen``` Our nav currently don't look good on a small screen. Kindly check the images for reference and work with it
smn1
```Original```
smn
* Currently, the latest news section does not look good. Check image below
smln
```Original```
smln1
* Currently, the Opinion section needs fixing
smop
```Original```
smop1
* Culture and Travel section needs to be fixed. We are missing the contents. Currently
smc
```Original```
smc1
* More Stories section can be improved. Check images for reference
smmore
```Original```
smmore1
* Let us address the following US, WORLD, BUSINESS, etc and its responsiveness on a small screen. Currently
smres
```Original```
smres1
* Footer needs a little work, kindly check images for reference
smft
```Original```
smft1
```Medium Screen device```
* Let us fix the nav on medium screen. Currently
mdn
```Original```
mdn1
* Top story and Featured stores, let us fix the width to make it look like the original. Currently
mdmain1
```Original```
mdmain
* Let us fix the overlapping text in the latest news section. Currently
mdln
```Original```
mdln1
* Let us fix the padding between the image and the text so it looks like the original. Currently
mdr
```Original```
mdr1
* Let us check how the footer looks currently and compare to the original
* Let us add hover effects like it is in the original

Kindly make these changes and submit another code review 😄 
_Happy coding_ 👨‍💻 
You can find me on slack on Daniel Larbi Addo

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello! My name is Mario. Congratulations on your project! You implemented quite a few required changes👍 🏅 

However there are a few things that still need to be fixed:

## Required changes

- [ ] You are still missing the search icon on your search bar

- [ ] Your Navbar is not behaving as expected, please try to fix the media queries for better responsiveness .

img1

- [ ] The general layout is wrong on some resolutions as shown in the screenshot below. Please be sure to use the correct alignment and resizing for all of the page elements.

img1

## Optional changes

- [x] I recommend you to use the developer tools and compare your project with the original testing at least the 5 more common resolutions (the sizes from bootstrap). This will help you to find mistakes before re-submitting the project.

- [ ] There are some repeated rules on your CSS (`display: block` for example is used 4 times). You can read this article is you need more reference: https://speckyboy.com/good-bad-css-practices/


Overall you did a good job but the key here is attention to detail 😄  However I'm sure you will have no problems fixing or implementing the required changes. After doing so, please resubmit your project for review.


## Code review by Mario Enrique Delgado Naranjo

**Comment by uryelah** [comment]
Hello **Maurice**, I'm Sarah, your reviewer for this PR 👩‍🚀  

I see you've made some improvements since the last review. Good job! 👏
I especially like your use of CSS variables, it's very smart.

As this project requires great attention to detail and responsiveness to the [original site](https://www.newsweek.com/), there are still issues to fix before moving on. You got this!💪 

---------    

### Required changes 🛠 
---------

As mentioned by the last TSE, part of your site layout and elements breaks on screen resizes. Remember to use the [responsive design mode of your browser](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode) to test how your clone behaves on resize. 

- [x] Please fix the overlapping text on medium to small screens:
Screenshot_2020-03-22 NewsWeek(15)
-----
- [x] Please fix the image and text overlap at the `Subscribe` section on  medium to small screen sizes:
Screenshot_2020-03-22 NewsWeek(16)
-----

- [x] Fix the `z-index` issue of the 'Subscribe' sections image. Make sure it's not above the navbar.
Screenshot_2020-03-22 NewsWeek(17)

**The original version:**
Screenshot_2020-03-22 Newsweek(18)

-------

- [x] Please fix the flex `justify` issue on the articles below for small screens. Compare your version and the original one.
**Your version:**
Screenshot_2020-03-22 NewsWeek(20)
**Original version:**
Screenshot_2020-03-22 Newsweek(19)
------
**Your version:**
Screenshot_2020-03-22 NewsWeek(21)
**Original versoin:**
Screenshot_2020-03-22 Newsweek(22)
------

- [x] The 'Top Story' category text should be over the images, not bellow. 
Compare your version with the original bellow:
**Your version:**
Screenshot_2020-03-22 NewsWeek(23)
**Original version:**
Screenshot_2020-03-22 Newsweek(24)
-----

- [x] Good job with the scroll on 'More stories', but do you need a scroll on both the X and the Y axis? Try to hide it while making it still scroll vertically. [Check this for help on scroll visibility.](https://stackoverflow.com/questions/5820304/hidden-scrollbars-in-firefox-allows-scrolling-but-just-no-scrollbar)
Screenshot_2020-03-22 NewsWeek(25)
**The original site scroll is functional but not visible:**
Screenshot_2020-03-22 Newsweek(26)

--

- [ ] Fix the flex `justification` issue on the content of the navbar on medium to small screens:
Screenshot_2020-03-22 NewsWeek(27)
**Original version:**
Screenshot_2020-03-22 Newsweek(28)

-----

- [ ] The Logo is not resizing properly on medium to small screens. Remember to try resizing your clone with the responsive browser tools:
Screenshot_2020-03-22 NewsWeek(13)

**Original navbar with the logo at the correct size:**
Screenshot_2020-03-22 Newsweek(14)
------

- [ ] Good job adding the search icon, but its positioning is a bit chaotic while resizing down the page:
Screenshot_2020-03-22 NewsWeek(29)
**How the search icon and input should be positioned:**
Screenshot_2020-03-22 Newsweek(30)

------

Please make sure you read the required changes with a lot of attention and spend some time comparing the behavior of the [original site ](https://www.newsweek.com/) and your clone on screen resize. 

This project requires a lot of attention and care but it's what it takes to make good and responsive web interfaces. You got this!

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 🐱

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Nice work @Morrism1 👏🎉

Your project looks great and I must also commend the fact that you tried to use as less CSS as possible since this project is more bootstrap inclined.👍

However there are are a few requirements that need to be met before proceeding:👇

- [ ] REQUIRED - Kindly validate your HTML with this [tool](https://validator.w3.org/nu/) and work on the errors shown.

- [ ] REQUIRED - On medium screen your webpage looks this way [Screenshot]👇
ice_screenshot_20200326-140805


BUT IT'S SUPPOSED TO LOOK THIS WAY [SCREENSHOT]👇 
ice_screenshot_20200326-142533

* Make it cover the screen also you will notice that the sections( FEATURED STORIES and TOP STORY) are named on the original webpage, add noted section titles to yours too.

- [ ] REQUIRED - Amend the search input field, the input field and the search icon are out of place, kindly fix that.[Screenshot]👇
ice_screenshot_20200326-141157

- [ ] REQUIRED - Spread out the nav bar items on your page .
**This is yours**[Screenshot]👇
ice_screenshot_20200326-140522

**THIS IS WHAT IT'S SUPPOSED TO LOOK LIKE[SCREENSHOT]👇**
ice_screenshot_20200326-143806

- [ ] REQUIRED - Also kindly add the weather indicator icon as can be seen in the original webpage navbar above [Screenshot]👆

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by thsvr** [comment]
### **STATUS: PROJECT APPROVED** :1st_place_medal: :1st_place_medal: :1st_place_medal: 

Hi @Morrism1 :smile_cat: :smile_cat: 

Congrats for the hard work, you did a great job :100:  doing the required fixes, now your project looks beautiful and it was approved :fireworks: :fireworks: :fireworks:

Before you merge it to master, can you please fix these 2 errors that [this validator](https://validator.w3.org/nu/) are showing? **No need to submit again for another code review, I trust you will fix it**, it is simple :smile_cat: 

validator





### Optional Suggestions for the next project:

:v:  You can create a feature branch with a more descriptive name on the next projects, like ''main-page'' or ''newsweek-page'' instead of ''feature", for example. It will be more descriptive. :smile_cat: 

If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)

### **Happy coding and good luck on the next project** :computer: 

_Project reviewed by Thaís Vieira (TSE)_

**Pull request merged**
